In [1]:
import sys
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPool2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense
#importing libraries
import seaborn as sns
# Ignore the warnings
import warnings
warnings.filterwarnings("ignore")

In [2]:
train_df = pd.read_pickle('train100c5k_v2.pkl')
train_sam = train_df.sample(frac=0.20, random_state=42, replace=True)
train_dt = train_sam['data'].values
shapeI=[]
for i in train_dt:
    reshapeI = i.reshape(28,28)
    shapeI.append(reshapeI)
train_label = train_sam['target'].values
features = np.array(shapeI)
label = np.array(train_label)

In [3]:
print(train_dt.shape)

(100000,)


In [4]:
print(type(train_dt))

<class 'numpy.ndarray'>


In [5]:
print(train_dt)

[array([[  2,   7,  10,   7,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           4,  10,   9,   8,   7,   6,   5,   2,   0,   0,   0,   0,   0,
           0,   0],
        [  1,   2,   3,   2,   0,   0,   0,   0,   0,  13,  19,   0,   0,
           2,   3,   3,   2,   2,   2,   1,   1,   0,   0,   0,   0,   0,
           0,   0],
        [  0,   0,   0,   0,   2,  13,  26,  38,  47,  69,  72,  33,  12,
           0,   0,   0,   0,   0,   0,   0,   0,   1,   1,   1,   1,   1,
           1,   0],
        [  0,   0,   0,   0,  12,  41,  74, 105, 124, 142, 143,  92,  36,
           0,   0,   0,   0,   0,   0,   0,   0,   4,   5,   5,   5,   5,
           5,   2],
        [  0,   0,   0,   0,  37,  83, 132, 178, 204, 217, 215, 162,  75,
           4,   0,   0,   0,   0,   0,   0,   1,   6,   6,   6,   6,   6,
           6,   2],
        [  2,   8,  11,  33,  81, 134, 183, 229, 255, 255, 255, 225, 136,
          50,  11,   9,   8,   6,   5,   3,   0,   0,   0,   0,   0,   0,
           0

In [6]:
print(train_label)

[24 29 26 ... 60 46 17]


In [7]:
print(features)

[[[  2   7  10 ...   0   0   0]
  [  1   2   3 ...   0   0   0]
  [  0   0   0 ...   1   1   0]
  ...
  [  0   0   0 ...   1   1   0]
  [  0   2   2 ...   0   0   0]
  [  0   5   8 ...   0   0   0]]

 [[  0   0   0 ...   0   2   0]
  [  0   0   2 ...  77   0   1]
  [  0   2   0 ... 217  41   1]
  ...
  [  0   0   0 ...   3   3   0]
  [  0   0   0 ...   1   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   4   7   0]
  [  0   0   0 ...   1   4   0]
  [  0   0   0 ...   0   3   0]]

 ...

 [[  0   0   0 ...   0   0   1]
  [  0   0   0 ...   0   0   6]
  [  0   0   0 ...   0   0   2]
  ...
  [  0   0  30 ...  25   0   4]
  [  1   2   1 ...   2   1   1]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...  46   0   1]
  [  0   0   0 ...  88   0   1]
  [  0   0   0 ... 145   0   1]
  ...
  [ 57 196 224 ...   0   0   0]
  [ 15 104 155 ...   0   0   0]
  [  0  50 116 ...   8   5  

In [9]:
print(features.shape)

(100000, 28, 28)


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, label, test_size = 0.2, random_state = 0)

In [11]:
print(X_train.shape)

(80000, 28, 28)


In [12]:
print(X_test.shape)

(20000, 28, 28)


In [13]:
print(X_train[0])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   6  52  91  53
    0   0   3   1   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   3   0   0  10  69 182 240 135
    0   0   6   1   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   4   0   0  25 125 225 236 119
    3   5  12   3   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   6   0   1  38 177 239 181  74
    0   0   0   0   6   6   2   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   4   0   0  60 218 251 149  60
   58 133 142  46   0   0   0   1   1   0]
 [  0   0   0   0   0   0   0   0   1   1   1   0  17  95 225 255 249 219
  219 252 255 201 152 108  46   1   0   3]
 [  0   0   0   0   0   0   0   0   2   2   0   2  49 147 245 214 147 165
  229 248 253 255 255 253 117   0   0   8]
 [  0   0   0   0   0   0   0   0   3   2   0   6  91 191 248 208 136 145
  209 246 255 250 202 136  58   1   1   4]
 [  0   0   0   0   0   0   0   1   4   4   2  12 137 219 213 22

In [14]:
#reshaping
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], X_train.shape[2], 1))
X_test = X_test.reshape((X_test.shape[0],X_test.shape[1],X_test.shape[2],1)) 
#after reshaping
print(X_train.shape)
print(X_test.shape)

(80000, 28, 28, 1)
(20000, 28, 28, 1)


In [15]:
#normalizing the pixel values
X_train=X_train/255
X_test=X_test/255

In [16]:
#defining model
model=Sequential()
#adding convolution layer
model.add(Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)))
#adding pooling layer
model.add(MaxPool2D(2,2))
#adding fully connected layer
model.add(Flatten())
model.add(Dense(100,activation='relu'))
#adding output layer
model.add(Dense(100,activation='softmax'))
#compiling the model
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
#fitting the model
model.fit(X_train,y_train,epochs=10)

Epoch 1/10
2500/2500 [==============================] - 16s 6ms/step - loss: 2.7582 - accuracy: 0.3501
Epoch 2/10
2500/2500 [==============================] - 17s 7ms/step - loss: 2.0848 - accuracy: 0.4922
Epoch 3/10
2500/2500 [==============================] - 20s 8ms/step - loss: 1.8898 - accuracy: 0.5355
Epoch 4/10
2500/2500 [==============================] - 19s 8ms/step - loss: 1.7497 - accuracy: 0.5659
Epoch 5/10
2500/2500 [==============================] - 19s 7ms/step - loss: 1.6425 - accuracy: 0.5895
Epoch 6/10
2500/2500 [==============================] - 21s 8ms/step - loss: 1.5500 - accuracy: 0.6107
Epoch 7/10
2500/2500 [==============================] - 19s 8ms/step - loss: 1.4661 - accuracy: 0.6288
Epoch 8/10
2500/2500 [==============================] - 18s 7ms/step - loss: 1.3867 - accuracy: 0.6479
Epoch 9/10
2500/2500 [==============================] - 21s 8ms/step - loss: 1.3132 - accuracy: 0.6643
Epoch 10/10
2500/2500 [==============================] - 19s 8ms/step - l

In [17]:
#evaluting the model
model.evaluate(X_test,y_test)

625/625 [==============================] - 1s 2ms/step - loss: 1.8718 - accuracy: 0.5558


[1.871780514717102, 0.5557500123977661]

In [18]:
y_pred = model.predict(X_test)

625/625 [==============================] - 1s 2ms/step


In [19]:
print(y_test.shape)

(20000,)


In [20]:
print(y_pred.shape)

(20000, 100)


In [21]:
print(y_pred)

[[6.6816806e-06 3.2433463e-04 2.9150015e-04 ... 2.0099924e-06
  2.2386219e-03 3.4973428e-07]
 [2.1573630e-06 3.9850108e-02 6.1601173e-04 ... 1.3701113e-04
  5.0497449e-05 6.9115323e-08]
 [7.7244016e-07 1.6752597e-06 3.2285874e-04 ... 1.8510809e-05
  2.5863228e-06 2.1223960e-07]
 ...
 [6.3426063e-07 1.7423266e-05 3.7038653e-08 ... 2.1464621e-04
  3.5101811e-03 6.8999251e-11]
 [3.1149677e-05 1.1603014e-08 1.9418239e-08 ... 4.8353758e-07
  1.1500071e-09 7.1112635e-07]
 [1.2281475e-08 8.4408342e-08 5.2701416e-05 ... 1.5532743e-05
  1.4395817e-05 4.0629104e-07]]


In [25]:
resultT=[]
for i in range(0,20000): 
    resultT.append(np.argmax(y_pred[i]))
    target=np.array(resultT)

In [26]:
print(target)

[32 11 55 ... 59 53 91]


In [31]:
#Comparing predicted and actual values of train set
print(np.concatenate((target.reshape(len(target),1), y_test.reshape(len(y_test),1)),1))

[[32 32]
 [11 11]
 [55 55]
 ...
 [59 60]
 [53 53]
 [91 91]]


In [32]:
test_df = pd.read_pickle('test100c5k_nolabel.pkl')
test_dt = test_df['data'].values
shapeIT=[]
for i in test_dt:
    reshapeI = i.reshape(28,28)
    shapeIT.append(reshapeI)
featuresT = np.array(shapeIT)


In [33]:
print(featuresT.shape)

(100000, 28, 28)


In [34]:
X_test_ = featuresT.reshape((featuresT.shape[0], featuresT.shape[1], featuresT.shape[2], 1))

In [35]:
X_test_=X_test_/255

In [36]:
y_predict = model.predict(X_test_)

3125/3125 [==============================] - 7s 2ms/step


In [37]:
print(y_predict.shape)

(100000, 100)


In [38]:
print(y_predict)

[[9.7389668e-03 6.5200780e-08 1.3923024e-07 ... 4.6891988e-09
  1.0591553e-07 1.0257549e-04]
 [1.8314588e-01 1.9529016e-09 9.1457009e-10 ... 1.3001712e-09
  1.1348047e-08 1.0186003e-04]
 [3.5629200e-05 2.3778388e-04 1.2290571e-02 ... 1.1366396e-06
  1.0044728e-03 9.1755772e-03]
 ...
 [7.4914147e-13 2.2950342e-09 5.8473552e-07 ... 6.5079321e-06
  8.9870284e-08 2.0204284e-10]
 [9.7990841e-01 8.2770839e-06 3.9119268e-09 ... 1.0218856e-09
  3.6033132e-09 9.0668975e-05]
 [3.1773832e-03 8.7588956e-04 6.7516265e-04 ... 1.9906760e-05
  1.7287469e-04 2.7236265e-05]]


In [40]:
result=[]
for i in range(0,100000): 
    result.append(np.argmax(y_predict[i]))
    

In [41]:
result=np.array(result)

In [42]:
print(result)

[77 50 33 ... 63  0 33]


In [43]:
with open('project_kashmira.txt', 'w') as file:  # edit here as your username
    file.write('\n'.join(map(str, result)))
    file.flush()

In [ ]:
# def run(train_image, train_label, test_image):
#     model = KNeighborsClassifier(n_neighbors=5)
#     data = [x.reshape(28 * 28, ) for x in train_image]
#     model.fit(data, train_label)

#     data = [x.reshape(28 * 28, ) for x in test_image]
#     result = model.predict(data)
#     with open('project_kashmira.txt', 'w') as file:  # edit here as your username
#         file.write('\n'.join(map(str, result)))
#         file.flush()
#         return True
#     return False

In [ ]:
# if __name__ == "__main__":
#     # we will run your code by the following command
#     # python project_xiaoq.py argv[1] argv[2]
#     # argv[1] is the path of training set
#     # argv[2] is the path of test set
#     # for example, python demo.py train100c5k_v2.pkl test100c5k_nolabel.pkl

#     try:
#         df = pd.read_pickle('train100c5k_v2.pkl')  # training set path
#         train_data = df['data'].values
#         train_target = df['target'].values
#         df = pd.read_pickle('test100c5k_nolabel.pkl')  # test set path
#         test_data = df['data'].values
#         info = run(train_data, train_target, test_data)
#         if not info:
#             print(sys.argv[0] + ": Return False")
#     except RuntimeError:
#         print(sys.argv[0] + ": An RuntimeError occurred")
#     except:
#         print(sys.argv[0] + ": An exception occurred")